# Generated by Django 5.1 on 2025-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='coordinates',
            field=models.CharField(blank=True, help_text="Enter latitude and longitude in the format: 'latitude,longitude'", max_length=100),
        ),
    ]
